version: '3.9'

services:
  web:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    environment: 
      - FLASK_SERVER_PORT=5001
    ports:
      - '5001:5001'
    volumes:
      - .:/code
    restart: always
    networks:
      - db-networks
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./instance/:/root/db/
    restart: always
    networks:
      - db-networks

networks:
    db-networks:
        driver: bridge





